name: flutter_oib_2023
description: Applicazione di Demo per l'introduzione di Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.1.10
  # Gestione delle variabili d'ambiente
  envied: ^0.3.0
  # Gestione dello stato dell'applicazione
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.0.2
  # Gestione griglie di contenuti
  flutter_staggered_grid_view: ^0.6.2
  # Gestione di models e json di risposta
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  # Gestione routing e navigazione
  go_router: ^6.5.1
  # Chiamate HTTP ad API esterne
  http: ^0.13.5
  # Gestione della finestra su Desktop
  window_manager: ^0.3.1
  #Integrazione con piattaforme desktop
  fluent_ui: ^4.4.0 # Windows
  macos_ui: ^1.12.2 # macOS
  yaru: ^0.6.2 # Linux/Ubuntu
  yaru_widgets: ^2.3.1 # Linux/Ubuntu

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true
