name: flutter_oib_2023
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  envied: ^0.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2
  freezed_annotation: ^2.2.0
  go_router: ^6.5.1
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^2.0.2
  url_launcher: ^6.1.10
  window_manager: ^0.3.1

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4

flutter:

  uses-material-design: true
